// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDknbJkJca9e6Yrk8yRfWzyUNvnpJY63LQ',
    appId: '1:630207092922:web:f8fd5bbc525422cee64a83',
    messagingSenderId: '630207092922',
    projectId: 'quizapp-94908',
    authDomain: 'quizapp-94908.firebaseapp.com',
    storageBucket: 'quizapp-94908.firebasestorage.app',
    measurementId: 'G-5JK8DF0YN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARZMErikvVMKeGOtF4j4-nla-IHq7gYFE',
    appId: '1:630207092922:android:81f1ef8400d8032ee64a83',
    messagingSenderId: '630207092922',
    projectId: 'quizapp-94908',
    storageBucket: 'quizapp-94908.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDknbJkJca9e6Yrk8yRfWzyUNvnpJY63LQ',
    appId: '1:630207092922:web:a17c38c325abdf13e64a83',
    messagingSenderId: '630207092922',
    projectId: 'quizapp-94908',
    authDomain: 'quizapp-94908.firebaseapp.com',
    storageBucket: 'quizapp-94908.firebasestorage.app',
    measurementId: 'G-9Z8T4H1BJB',
  );
}
